### ISSUE TITLE
Issue with calc --report/vasp.relax.report on Conda install

### ISSUE THREAD

**Issue by Erothch** [prisms-center/CASMcode#120]
Dear developers,
 I am having issues with casm-calc --report, hopefully you can help with this.

I am running casm on Scientific Linux 7, installed using Conda (as “`conda create -n casm --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge casm`”). To start off with I am working through the ZrO input example. I have successfully set up my VASP input files in each folder by running “casm calc –setup.” 

Each folder cas_demo/ZrO/training_data/SCEL*/*/calctype.default has the correct files POSCAR, INCAR, KPOINTS, POTCAR. I then run VASP in that directory to create the output files, including vasprun.xml.  I am running VASP in this directory using my own job submission script instead of using Prisms_Jobs due to requirements in job submission files on this cluster. 

After the run completes, the folder cas_demo/ZrO/training_data/SCEL*/*/calctype.default contains the appropriate output files including vasprun.xml. However, when I run “`casm-calc –report`” it give the following output:
“Unable to report properties for directory /cas_demo/ZrO/training_data/SCEL1_1_1_1_0_0_0/0.
Please verify that it contains a completed calculation.” For each folder, whether or not I have run the calculation in it.

I tried going into /cas_demo/ZrO/training_data/SCEL1_1_1_1_0_0_0/0 to run `vasp.relax.report ./` to make the properties json file that way and I get the error ...".conda/envs/casm/lib/python3.6/site-packages/casm/scripts/vasp_relax_report.py", line 25, in main
    compat.dump(json, output, 'properties.calc.json', 'w', cls=noindent.NoIndentEncoder,
AttributeError: module 'casm.misc.compat' has no attribute 'dump'"

Please let me know if you know what I need to do to fix this.

Best,
Eric

**Comment by bpuchala** [comment]
Thank you for raising this issue.

It is often the case that multiple runs of a DFT calculation may be necessary to complete a calculation.  The standard CASM way of organizing this is to use:
```
casm_demo/ZrO/training_data/SCEL*/*/calctype.*/run.0
casm_demo/ZrO/training_data/SCEL*/*/calctype.*/run.1
casm_demo/ZrO/training_data/SCEL*/*/calctype.*/run.2
...
casm_demo/ZrO/training_data/SCEL*/*/calctype.*/run.final
```

The ```casm calc --report``` command reads the VASP output in the ```run.final``` directory and generates ```casm_demo/ZrO/training_data/SCEL*/*/calctype.*/properties.calc.json```. It sounds like it is trying to read from there and not finding it and giving you the error. 

It does appear that the ```run.final``` directory expectation for ```--report``` is not documented and needs to be.

Hopefully, if you create these ```run.final``` directories and move your VASP results into those then the ```--report``` command will work. Please let me know if this does not fix this issue.

**Comment by Erothch** [comment]
Thank you for the quick response, however the problem persists.

Created directories `casm_demo/ZrO/training_data/SCEL*/*/calctype.default/run.final` (also tried with directories run.0 run.1 and run.2 present and filled) and moved vasp output to it, I get the same error upon running `casm calc --report` and `vasp.relax.report` as before.

**Comment by bpuchala** [comment]
OK, I missed that.  There are three files where I believe the following changes are needed:

`python/casm/casm/scripts/casm_calc.py`:
```
-          compat.dump(json, output, calc_props, 'w', cls=noindent.NoIndentEncoder, indent=4, sort_keys=True)
+          with open(calc_props,'wb') as file:
+              file.write(six.u(json.dump(output, file, indent=4, sort_keys=True, cls=noindent.NoIndentEncoder)).encode('utf-8'))
```

`python/casm/casm/scripts/qe_relax_report.py`:
```
-    compat.dump(json, output, 'properties.calc.json', 'w', cls=noindent.NoIndentEncoder, 
-                indent=4, sort_keys=True)
+    with open('properties.calc.json','wb') as file:
+        file.write(six.u(json.dump(output, file, indent=4, sort_keys=True, cls=noindent.NoIndentEncoder)).encode('utf-8'))
```

`python/casm/casm/scripts/vasp_relax_report.py`:
```
-    compat.dump(json, output, 'properties.calc.json', 'w', cls=noindent.NoIndentEncoder, 
-                indent=4, sort_keys=True)
+    with open('properties.calc.json','wb') as file:
+        file.write(six.u(json.dump(output, file, indent=4, sort_keys=True, cls=noindent.NoIndentEncoder)).encode('utf-8'))
```

You can try making these changes directly or wait a little bit for a new conda package. 

I will be working on writing new tests to check this and a couple related things. I'll update this issue when I have an updated conda dev package with fixes released.

**Comment by Erothch** [comment]
I tried making these changes, I still cannot get casm calc --report to find the output (now it writes a blank file) but I can get vasp.relax.report to write properties.calc.json correctly if I use:
`with open('properties.calc.json','w') as file:
        file.write(json.dumps(output, indent=4, sort_keys=True, cls=noindent.NoIndentEncoder))`

And these results go into the config list properly when using `casm update`.

As it was written above vasp.relax.report was giving me type errors (which I think may be a compatibility between python 2 and 3 issue but I am unsure.

Thanks for the help! I think I can get by with building my properties files this way for now, and I'll be on the lookout for the update in the future.

-eric
