### ISSUE TITLE
PRIM with two sites at the same point has symmetry/equivalency issues

### ISSUE THREAD

**Issue by tallakahath** [prisms-center/CASMcode#23]
The short: If you try to make a CASM project with two different DOFs on top of each other (A/B and C/D), CASM somehow considers SCELs containing A+C and B+D to be "the same", which feels like a very weird symmetry issue.

The long:

Consider the following prim.json:

``` json
{
  "basis" : [
    {
      "coordinate" : [ 0.000000000000, 0.000000000000, 0.000000000000 ],
      "occupant_dof" : [ "A", "B" ]
    },
    {
      "coordinate" : [ 0.500000000000, 0.500000000000, 0.500000000000 ],
      "occupant_dof" : [ "C", "D" ]
    }
  ],
  "coordinate_mode" : "Fractional",
  "description" : "FooBar",
  "lattice_vectors" : [
    [ 0.000000000000, 1.000000000000, 1.000000000000 ],
    [ 1.000000000000, 0.000000000000, 1.000000000000 ],
    [ 1.000000000000, 1.000000000000, 0.000000000000 ]
  ],
  "title" : "ABCD"
}
```

Here I have two DOFs: A/B on the first site, and C/D on the second site. I can init a project with this, run `casm enum --max 1 -s ; casm enum -a -c` and get 4 configs in SCEL1:
- A C
- A D
- B C
- B D

This seems reasonable and perfectly well behaved. Now, instead, I have Good Reasons to want to put two sites _literally_ on top of each other. I have the following prim:

``` json
{
  "basis" : [
    {
      "coordinate" : [ 0.000000000000, 0.000000000000, 0.000000000000 ],
      "occupant_dof" : [ "A", "B" ]
    },
    {
      "coordinate" : [ 0.000000000000, 0.000000000000, 0.000000000000 ],
      "occupant_dof" : [ "C", "D" ]
    }
  ],
  "coordinate_mode" : "Fractional",
  "description" : "FooBar",
  "lattice_vectors" : [
    [ 0.000000000000, 1.000000000000, 1.000000000000 ],
    [ 1.000000000000, 0.000000000000, 1.000000000000 ],
    [ 1.000000000000, 1.000000000000, 0.000000000000 ]
  ],
  "title" : "ABCD"
}
```

Problems begin with `casm init`. CASM complains that the structure in prim.json is not primitive, and prints me a prim.true.json. However, this prim is _identical_ to prim.json, line-for-line. Copying this new prim.true.json to prim.json and re-running `casm init` produces the same error.

OK, I run `casm init -f` now to move on. And CASM chugs along! Now I run `casm enum --max 1 -s ; casm enum -a -c` and get _3_ configs in SCEL1:
- A C
- B C
- B D

Weird, where did A D go? I create the following POS:

```
SCEL1_1_1_1_0_0_0/3
1.00000000
                       0.00000000       1.00000000       1.00000000
                       1.00000000       0.00000000       1.00000000
                       1.00000000       1.00000000       0.00000000
A D 
1 1 
Direct
               0.0000000    0.0000000    0.0000000 A
               0.0000000    0.0000000    0.0000000 D
```

And run `casm import -p POS`. CASM returns:

>   Beginning import of 1 configuration...
> 
>  "/home/liz/prim_tests/ABCD_3/POS"
>  mapped onto pre-existing equivalent structure SCEL1_1_1_1_0_0_0/1
> 
>  Relaxation stats -> lattice_deformation = 0      basis_deformation = 0

That's not right! SCEL1/1 is B C, not A D! For some reason, CASM thinks these two are the same! 

What went wrong here? I know I'm doing something "really weird" putting two DOFs on top of each other, but its still a scary failure mode.

**Comment by jcthomas** [comment]
Yeah, I think this is an uncommon usage case, but it's easy to fix, so I
think we should allow it.  The issue was due to how sites were compared for
purposes of determining the primitive cell and constructing certain
symmetry representations. I pushed a fix to my fork and will open a pull
request.

On Thu, Oct 27, 2016 at 11:37 AM, Liz Decolvenaere <notifications@github.com

**Comment by tallakahath** [comment]
@jcthomas Alas, your fix doesn't fully fix it. When enumerating clusters with my "distorted" prim (site B not exactly atop site A), I get clusters that couple the 'A' and 'B' sites that are reaaaaaally close together (max and min lengths of the cluster are very small). However, when I use the "perfect" prim (A and B atop each other), I do NOT get any clusters that have both the A and B sub-lattices at the same site (e.g., no NN pair with a max_length of 0). This means I'm entirely losing my chemo-magnetic on-site interactions D:

**Comment by jcthomas** [comment]
Did you try specifying "min_length" : -1 in your bspecs.json?

**Comment by tallakahath** [comment]
Just tried it now with a bspecs.json of:

```
{
  "basis_functions" : {
    "site_basis_functions" : "chebychev"
  },
  "orbit_branch_specs" : {
    "2" : {
        "min_length" : -1.0,
        "max_length" : 6.30
    },
    "3" : {
        "min_length" : -1.0,
        "max_length" : 6.30
    },
    "4" : {
        "min_length" : -1.0,
        "max_length" : 6.30
    }
  }
}
```

No luck, the only length-0 clusters being made are the empty and point
clusters.

**Comment by tallakahath** [comment]
I'm trying to figure out where I'd need to change things still, but I think
the problem has to do with how min_length and TOL interact with each other.

**Comment by jcthomas** [comment]
I forgot that "min_length" is deprecated. Updated my pull request. Let me
know if you run into any other issues.

**Comment by tallakahath** [comment]
Crashes. Even if I don't put a min_length in bspecs.json, I get:


-- Generate: Cluster orbits --
casm: ../include/casm/container/Array.hh:142: T&
CASM::Array<T>::operator[](CASM::Index) [with T = long int; CASM::Index =
long int]: Assertion `ind >= 0 && ind < N' failed.
Aborted (core dumped)

**Comment by jcthomas** [comment]
What is your `bspecs.json`?  I'm unable to reproduce the error, even in
debug mode.

**Comment by tallakahath** [comment]
{
  "basis_functions" : {
    "site_basis_functions" : "chebychev"
  },
  "orbit_branch_specs" : {
    "2" : {
        "min_length" : -1.0,
        "max_length" : 6.30
    },
    "3" : {
        "min_length" : -1.0,
        "max_length" : 6.30
    },
    "4" : {
        "min_length" : -1.0,
        "max_length" : 6.30
    }
  }
    }
  ]
}

I have also tried it with "min_length" : 0.0,

Which produces the same failure.

casm: ../include/casm/container/Array.hh:142: T&
CASM::Array<T>::operator[](CASM::Index) [with T = long int; CASM::Index =
long int]: Assertion `ind >= 0 && ind < N' failed.

Does your PRIM have two sites atop each other in your test?

-Liz D

**Comment by jcthomas** [comment]
I'm using the same PRIM that you specified at the top of the thread. There
are two extra closing brackets in your `bspecs.json` file, but that doesn't
cause an error for me.

I didn't try it out with the 6.3-Angstr max_length (because it was going to
take forever), but I did try with 3.0 Angstr max_length, which did work
(producing 563 clusters).

You might want to try a smaller max_length and see if that works.  It's
possible (but unlikely) that it's due to an integer overflow.  If you can
get the call stack from gdb/lldb I might be able to diagnose.

**Comment by tallakahath** [comment]
I am doing it with a prim that also has non-variational basis sites. Can
you try adding a third basis site to your prim at [X, Y, Z] with DOF ["C"]
and see if that breaks it? Otherwise I'm at a loss.

-Liz D

**Comment by tallakahath** [comment]
Hm, testing with even a simple PRIM and bspecs.json I'm getting the error.
I'm going to go check my source code files...

**Comment by jcthomas** [comment]
I tried with the fixed-occupancy site, and it worked (at both a high-sym
and low-sym position).

It should be easy to find the where the out-of-bounds access is occurring
with a debugger.

**Comment by tallakahath** [comment]
OK, found the problem. I was cherry-picking your code fixes into another branch... still not sure why they're not compatible with that branch (where "that branch" is something I rather desperately also need), but, your branch (vanilla) compiles and works just fine for me.

**Comment by tallakahath** [comment]
OK everything works for me now. Thanks for the patches!
